version = 0.1
[default.deploy.parameters]
stack_name = "terraform-75"
resolve_s3 = true
s3_prefix = "terraform-75"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BucketName=\"pgr301-couch-explorers\" CandidateNumber=\"75\" ModelId=\"amazon.titan-image-generator-v1\""
image_repositories = []
